name: Linux
on:
  push:
    branches:
      - main

jobs:
  run-danger:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install swiftly
      shell: bash
      run: curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash -s -- -y
    - name: Install the latest Swift toolchain
      run: swiftly install latest
    - name: Build and run tests
      run: swift build